# dmr_report.py — CLEAN, DETERMINISTIC DMR PAYLOAD
from __future__ import annotations

from typing import Dict, Any
from datetime import datetime, timezone

from trade_logic_v2 import build_trade_logic_summary


def _today_utc_str() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d")


def compute_dmr(symbol: str, inputs: Dict[str, Any]) -> Dict[str, Any]:
    """
    Returns a deterministic payload:
    - levels: daily support/resistance + breakout/breakdown triggers
    - range_30m: opening range high/low
    - htf_shelves: resistance/support arrays
    - report_text: *optional* (AI populates in main.py)
    """
    symbol = (symbol or "").strip().upper()
    if not symbol:
        raise ValueError("symbol is required")

    # inputs must already contain the computed levels/ranges from your data_feed pipeline
    levels = inputs.get("levels") or {}
    range_30m = inputs.get("range_30m") or {}
    htf_shelves = inputs.get("htf_shelves") or {}

    # Build trade logic outlook (THIS is where your crash came from in production)
    trade_logic = build_trade_logic_summary(
        symbol=symbol,             # <— REQUIRED, ALWAYS PASSED
        levels=levels,
        range_30m=range_30m,
        htf_shelves=htf_shelves,
        inputs=inputs,
    )

    payload = {
        "symbol": symbol,
        "date": inputs.get("date") or _today_utc_str(),
        "inputs": inputs,
        "levels": levels,
        "range_30m": range_30m,
        "htf_shelves": htf_shelves,
        "trade_logic": trade_logic,
        # report/report_text is generated by OpenAI in main.py; deterministic compute stays pure.
    }
    return payload
